### ISSUE TITLE
Please update the C/C++ on Graviton page with Graviton3 flags

### ISSUE THREAD

**Issue by acmorrow** [aws/aws-graviton-getting-started#177]
With today's announcement of Graviton3, it would be useful to have the tables at https://github.com/aws/aws-graviton-getting-started/blob/main/c-c%2B%2B.md updated with the optimal flags.

**Comment by AWSNB** [comment]
@acmorrow Gv3 should use same as Gv2,   in general, all code optimized for Gv2 should work really well on Gv3

we will update the docs to reflect that

**Comment by coderodyhpc** [comment]
Hello,
I was going to open a new thread when I bumped into this one, which has many commonalities with my questions:
1 - I thought that Graviton3 was going to be armv8.4-a instead of armv8.2-a (I honestly cannot recall where I read it but it'd be surprising if it were the same minor version).
2 - Graviton3 incorporates a bunch of new flags (`jscvt fcma lrcpc dcpop sha3 sm3 sm4 asimddp sha512 sve asimdfhm dit uscat ilrcpc flagm paca pacg svei8mm svebf16 i8mm bf16 dgh rng`). I still haven't found the time to investigate several of them, but does any of them have any effect on the GCC (later versions) flags?
Thanks.

**Comment by AGSaidi** [comment]
#219 addresses this. 

Beyond SVE none of those flags will be cause the compiler to emit instructions and they'll only be emitted from assembly/instrinsics.
